            <div class="container page-container">
                <div class="row">
                    <div class="jumbotron">
                        <h3><img src="img/about.png" /> Professional tools</h3>
	                    <p>Offline signing: Save Page As ... <a href="/offlinesign.html" target="_blank">offline sign page</a>.</p>
                            <p>Latest <a href="/index.html?currency=TMSC&filter=accept">TMSC deals</a>.</p>
	                    <p>Live <a href="/general/difference.json">consensus checker</a> between masterchain.info and mastercoin-explorer.com</p>
                            <p></p>
                    </div>
                </div>
            </div>
