            <div class="container page-container">
                <div class="row">
                    <div class="jumbotron">
                        <h3><img src="img/about.png" /> About</h3>
	                    <p>This is the web UI of <a href="https://github.com/grazcoin/mastercoin-tools" target="_blank">mastercoin-tools</a> (<a href="License.html">License</a>).</p>
                            <p>This project was done as part of <a href="http://mastercoin.org">Mastercoin</a> coding <a href="https://bitcointalk.org/index.php?topic=292628.0">contest</a>.</p>
	                    <p>Sync to bitcoin network is done using <a href="https://github.com/spesmilo/sx">sx</a> which connects to a local <a href="https://github.com/spesmilo/obelisk">obelisk</a> bitcoin node.</p>
                            <p>Links to <a href="/professional.html">additional tools</a>.</p>
                            <p></p>
                            <p>Developers: <a href="https://bitcointalk.org/index.php?action=profile;u=61204">Grazcoin</a> and <a href="https://bitcointalk.org/index.php?action=profile;u=153554">Grimentz</a>.</p>
                    </div>
                </div>
            </div>
