            <div class="container page-container">
              <div class="row">
                <div class="jumbotron">
                  <h3><img src="img/about.png" />API</h3>
                  <p>http://masterchain.info/tx/$TX_ID.json (e.g. <a href="http://masterchain.info/tx/546a406a131089e7c2f27d34a93a4d27441d98d096404d6737c5ad5b5e61a09b.json">here</a>)</p>
                  <p>http://masterchain.info/addr/$ADDRESS.json (e.g. <a href="http://masterchain.info/addr/1PA8qhEzW7to6EeqBAdhVZYGbVj2MfmN2n.json">here</a>)</p>
                  <p>http://masterchain.info/general/$CURRENCY_$PAGE.json (e.g. <a href="http://masterchain.info/general/MSC_0000.json">here</a>)</p>
                </div>
            </div>
