            <div class="container page-container">
              <div class="row">
                <div class="jumbotron">
                  <h3><img src="img/license.png" />License</h3>
	              <p>The <a href="https://github.com/grazcoin/mastercoin-tools/">code</a> is distributed under <a href="http://www.gnu.org/licenses/agpl-3.0-standalone.html" target="_blank">AGPL v3</a> license.</p>
                  <p>This site uses <a href="http://glyphicons.com" target="_blank">glyphicons</a> fonts.</p>
                </div>
              </div>
            </div>
